version: '3.9'

services:
  classification_app:
    container_name: classification_demo
    image: "${DOCKER_REGISTRY}/classification_demo:0.0.2"
    build:
      context: .
      dockerfile: Dockerfile
    command: python app.py
    restart: always
    volumes:
      - .:/workspace
    ports:
      - "8000:8000"
      - "8080:8080"
    env_file:
      - .env
